---
# URL of the webhooks to send POST events to
webhooks:
  - webhook url here

# The list of events you want broadcasted.
# See the latest manual here for a list of possible events:
# https://forums.frontier.co.uk/showthread.php/275151-Commanders-log-manual-and-data-sample
# They are case-sensitive.
events:
  - Docked
  - Undocked
  - WingJoin
  - FSDJump
  - SendText
  - RedeemVoucher
  - Died
  - USSDrop
  - SelfDestruct
